-- Activity & security upgrade for Client Dashboard
-- Run this file once in Supabase > SQL Editor.
-- Safe to re-run: functions, triggers, indexes and policies are idempotent.

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  details text,
  created_at timestamptz not null default now()
);

create index if not exists activity_logs_user_created_idx
  on public.activity_logs (user_id, created_at desc);

alter table public.activity_logs enable row level security;

-- Keep profile email synchronized and automatically create a client profile.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    'client'
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = case
      when public.profiles.full_name is null or public.profiles.full_name = ''
      then excluded.full_name
      else public.profiles.full_name
    end,
    updated_at = now();

  if tg_op = 'INSERT' then
    insert into public.activity_logs (user_id, action, details)
    values (new.id, 'account_created', 'Account registered');
  end if;

  return new;
end;
$$;

-- Record the first time an account email becomes confirmed.
create or replace function public.log_email_confirmation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.email_confirmed_at is null and new.email_confirmed_at is not null then
    insert into public.activity_logs (user_id, action, details)
    values (new.id, 'email_confirmed', 'Email address confirmed');
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.handle_new_user();

drop trigger if exists on_auth_email_confirmed on auth.users;
create trigger on_auth_email_confirmed
after update of email_confirmed_at on auth.users
for each row execute function public.log_email_confirmation();

-- RLS: users can read and write only their own activity; admins can read all.
drop policy if exists "Users can view own activity" on public.activity_logs;
drop policy if exists "Users can insert own activity" on public.activity_logs;
drop policy if exists "Admins can view all activity" on public.activity_logs;

create policy "Users can view own activity"
on public.activity_logs for select to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own activity"
on public.activity_logs for insert to authenticated
with check (auth.uid() = user_id);

create policy "Admins can view all activity"
on public.activity_logs for select to authenticated
using (public.is_admin());

grant select, insert on public.activity_logs to authenticated;
grant usage, select on sequence public.activity_logs_id_seq to authenticated;

-- Events now recorded by the application/database:
-- account_created            database trigger
-- email_confirmed            database trigger
-- signed_in                  application after successful sign-in
-- signed_out                 application before sign-out
-- profile_updated            profile API
-- password_changed           authenticated Security settings
-- password_reset_completed   password recovery flow
-- admin_role_updated         admin API (actor audit event)
--
-- A password-reset REQUEST is intentionally not stored against a user.
-- That endpoint is unauthenticated; avoiding a user lookup prevents account
-- enumeration and keeps the audit log tied to authenticated/verified actions.
