"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import Brand from "@/components/Brand";
import { CheckIcon, ShieldIcon } from "@/components/Icons";

export default function UpdatePasswordPage(){
  const router=useRouter();const [password,setPassword]=useState("");const [confirmPassword,setConfirmPassword]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  const req={length:password.length>=8,uppercase:/[A-Z]/.test(password),lowercase:/[a-z]/.test(password),number:/[0-9]/.test(password),special:/[^A-Za-z0-9]/.test(password)};const valid=Object.values(req).every(Boolean);const match=password.length>0&&password===confirmPassword;
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");if(!valid){setError("Password does not meet all requirements.");return;}if(!match){setError("Passwords do not match.");return;}setLoading(true);const supabase=createClient();const {error}=await supabase.auth.updateUser({password});if(error){setError(error.message);setLoading(false);return;}await supabase.auth.signOut();router.push("/login");router.refresh();}
  return <main className="min-h-screen bg-[#f7f9fc] px-6 py-8"><div className="mx-auto max-w-6xl"><Brand/><div className="mx-auto mt-16 max-w-md rounded-[28px] border border-slate-200 bg-white p-8 shadow-[0_28px_70px_-35px_rgba(15,23,42,0.35)] sm:p-10"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-600"><ShieldIcon className="h-6 w-6"/></div><h1 className="mt-6 text-3xl font-black tracking-[-0.03em] text-slate-950">Create a new password</h1><p className="mt-3 leading-7 text-slate-500">Choose a strong password you haven&apos;t used before.</p><form onSubmit={submit} className="mt-7 space-y-5"><PasswordField label="New password" value={password} setValue={setPassword}/>{password.length>0&&!valid&&<div className="grid grid-cols-2 gap-2 rounded-xl border border-slate-200 bg-slate-50 p-3">{Object.entries({"8+ characters":req.length,"Uppercase":req.uppercase,"Lowercase":req.lowercase,"Number":req.number,"Special character":req.special}).map(([label,ok])=><div key={label} className={`flex items-center gap-1.5 text-xs font-semibold ${ok?"text-emerald-600":"text-slate-400"}`}><span className={`grid h-4 w-4 place-items-center rounded-full ${ok?"bg-emerald-100":"bg-slate-200"}`}>{ok&&<CheckIcon className="h-3 w-3"/>}</span>{label}</div>)}</div>}<PasswordField label="Confirm new password" value={confirmPassword} setValue={setConfirmPassword}/>{confirmPassword.length>0&&!match&&<p className="text-sm font-medium text-red-600">Passwords do not match.</p>}{error&&<div className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm font-medium text-red-700">{error}</div>}<button disabled={loading||!valid||!match} className="w-full rounded-xl bg-blue-600 px-4 py-3.5 font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700 disabled:opacity-50">{loading?"Updating password...":"Update password"}</button></form></div></div></main>
}
function PasswordField({label,value,setValue}:{label:string;value:string;setValue:(v:string)=>void}){const id=label.toLowerCase().replaceAll(" ","-");return <div><label htmlFor={id} className="mb-2 block text-sm font-semibold text-slate-700">{label}</label><input id={id} type="password" value={value} onChange={(e)=>setValue(e.target.value)} required autoComplete="new-password" placeholder="••••••••" className="w-full rounded-xl border border-slate-300 px-4 py-3.5 outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-100"/></div>}
