import Link from "next/link";
import { requireAdmin } from "@/lib/auth";
import AppSidebar from "@/components/AppSidebar";
import RoleSelect from "./RoleSelect";
import { SearchIcon, ShieldIcon, UsersIcon, UserIcon, ArrowRightIcon } from "@/components/Icons";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ q?: string; role?: string }> }) {
  const { supabase, user, profile: adminProfile } = await requireAdmin();
  const params=await searchParams; const q=(params.q||"").trim(); const roleFilter=params.role==="admin"||params.role==="client"?params.role:"";
  let query=supabase.from("profiles").select("id,email,username,full_name,role,company,phone,created_at").order("created_at",{ascending:false});
  if(roleFilter)query=query.eq("role",roleFilter); if(q){const clean=q.replace(/[,%]/g,"");query=query.or(`full_name.ilike.%${clean}%,username.ilike.%${clean}%,email.ilike.%${clean}%,company.ilike.%${clean}%`);}
  const {data}=await query; const users=data??[]; const total=users.length; const admins=users.filter((x)=>x.role==="admin").length; const clients=users.filter((x)=>x.role==="client").length;
  const adminName=adminProfile?.full_name||user.email||"Administrator";
  return <main className="min-h-screen bg-[#f6f8fc] text-slate-950">
    <AppSidebar active="admin" name={adminName} email={user.email||"No email"} role="admin"/>
    <div className="lg:pl-72"><div className="mx-auto max-w-[1500px] px-5 py-7 sm:px-7 lg:px-10 lg:py-9">
      <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-violet-600">Administration</p><h1 className="mt-2 text-3xl font-black tracking-[-0.035em] sm:text-4xl">User management</h1><p className="mt-2 text-slate-500">Review accounts, manage roles and inspect user activity.</p></div><div className="inline-flex w-fit items-center gap-2 rounded-full border border-violet-100 bg-violet-50 px-3 py-1.5 text-xs font-bold text-violet-700"><ShieldIcon className="h-4 w-4"/> Administrator access</div></div>
      <div className="mt-8 grid gap-4 sm:grid-cols-3"><Stat icon={<UsersIcon className="h-5 w-5"/>} label="Visible users" value={total} tone="blue"/><Stat icon={<UserIcon className="h-5 w-5"/>} label="Client accounts" value={clients} tone="emerald"/><Stat icon={<ShieldIcon className="h-5 w-5"/>} label="Administrators" value={admins} tone="violet"/></div>
      <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_16px_40px_-30px_rgba(15,23,42,0.45)]">
        <div className="border-b border-slate-100 p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-black tracking-tight">Directory</h2><p className="mt-1 text-sm text-slate-500">Search by name, username, email or company.</p></div><form className="flex w-full flex-col gap-2 sm:flex-row lg:w-auto"><div className="relative sm:min-w-72"><SearchIcon className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input name="q" defaultValue={q} placeholder="Search users..." className="w-full rounded-xl border border-slate-300 py-2.5 pl-10 pr-4 text-sm outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-100"/></div><select name="role" defaultValue={roleFilter} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 outline-none focus:border-blue-500"><option value="">All roles</option><option value="client">Clients</option><option value="admin">Admins</option></select><button className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-bold text-white hover:bg-slate-800">Search</button>{(q||roleFilter)&&<Link href="/admin" className="rounded-xl border border-slate-200 px-4 py-2.5 text-center text-sm font-bold text-slate-600 hover:bg-slate-50">Clear</Link>}</form></div></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead><tr className="border-b border-slate-100 bg-slate-50/70 text-[11px] font-bold uppercase tracking-[0.1em] text-slate-400"><th className="px-6 py-4">User</th><th className="px-6 py-4">Company</th><th className="px-6 py-4">Joined</th><th className="px-6 py-4">Role</th><th className="px-6 py-4 text-right">Action</th></tr></thead><tbody>{users.map((item)=>{const name=item.full_name||"Unnamed user";const initials=name.split(" ").filter(Boolean).slice(0,2).map((p:string)=>p[0]?.toUpperCase()).join("")||"U";return <tr key={item.id} className="border-b border-slate-100 transition last:border-0 hover:bg-slate-50/70"><td className="px-6 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-slate-100 to-slate-200 text-xs font-black text-slate-700">{initials}</span><div><div className="flex items-center gap-2"><p className="font-bold text-slate-900">{name}</p>{item.id===user.id&&<span className="rounded-full bg-blue-50 px-2 py-0.5 text-[10px] font-bold text-blue-600">YOU</span>}</div><p className="mt-0.5 text-xs font-bold text-blue-600">{item.username ? `@${item.username}` : "No username"}</p><p className="mt-0.5 text-sm text-slate-500">{item.email||"No email"}</p></div></div></td><td className="px-6 py-4 text-sm font-medium text-slate-600">{item.company||"—"}</td><td className="px-6 py-4 text-sm font-medium text-slate-600">{new Date(item.created_at).toLocaleDateString()}</td><td className="px-6 py-4"><RoleSelect userId={item.id} role={item.role}/></td><td className="px-6 py-4 text-right"><Link href={`/admin/users/${item.id}`} className="inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-bold text-blue-600 transition hover:bg-blue-50">View <ArrowRightIcon className="h-3.5 w-3.5"/></Link></td></tr>})}</tbody></table>{users.length===0&&<div className="py-16 text-center"><SearchIcon className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-3 font-bold text-slate-700">No users found</p><p className="mt-1 text-sm text-slate-500">Try adjusting your search or filter.</p></div>}</div>
      </section>
    </div></div>
  </main>
}
function Stat({icon,label,value,tone}:{icon:React.ReactNode;label:string;value:number;tone:"blue"|"emerald"|"violet"}){const tones={blue:"bg-blue-50 text-blue-600",emerald:"bg-emerald-50 text-emerald-600",violet:"bg-violet-50 text-violet-600"};return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_14px_34px_-28px_rgba(15,23,42,0.5)]"><div className="flex items-center gap-4"><span className={`grid h-11 w-11 place-items-center rounded-xl ${tones[tone]}`}>{icon}</span><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-slate-400">{label}</p><p className="mt-1 text-3xl font-black tracking-tight">{value}</p></div></div></div>}
