"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import Brand from "@/components/Brand";
import { MailIcon, ChevronLeftIcon } from "@/components/Icons";

export default function ForgotPasswordPage(){
  const [email,setEmail]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
  async function handleSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");setSuccess("");const supabase=createClient();const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/auth/callback?next=/update-password`});if(error){setError(error.message);setLoading(false);return;}setSuccess("Reset instructions were sent to your email.");setLoading(false);}
  return <main className="min-h-screen bg-[#f7f9fc] px-6 py-8"><div className="mx-auto max-w-6xl"><Brand/><div className="mx-auto mt-20 max-w-md rounded-[28px] border border-slate-200 bg-white p-8 shadow-[0_28px_70px_-35px_rgba(15,23,42,0.35)] sm:p-10"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-600"><MailIcon className="h-6 w-6"/></div><h1 className="mt-6 text-3xl font-black tracking-[-0.03em] text-slate-950">Reset your password</h1><p className="mt-3 leading-7 text-slate-500">Enter your account email and we&apos;ll send a secure reset link.</p><form onSubmit={handleSubmit} className="mt-7 space-y-5"><div><label htmlFor="email" className="mb-2 block text-sm font-semibold text-slate-700">Email address</label><input id="email" type="email" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="you@example.com" required autoComplete="email" className="w-full rounded-xl border border-slate-300 px-4 py-3.5 outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-100"/></div>{error&&<div className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm font-medium text-red-700">{error}</div>}{success&&<div className="rounded-xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">{success}</div>}<button disabled={loading} className="w-full rounded-xl bg-blue-600 px-4 py-3.5 font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700 disabled:opacity-50">{loading?"Sending...":"Send reset link"}</button></form><Link href="/login" className="mt-6 flex items-center justify-center gap-1.5 text-sm font-bold text-slate-600 hover:text-blue-600"><ChevronLeftIcon className="h-4 w-4"/> Back to sign in</Link></div></div></main>
}
